# Create .netrc for private repo install
before_install:
- echo -e "machine github.com\n  login $GITHUB_AUTH_TOKEN" >> ~/.netrc
# Branch whitelist
branches:
  only:
    - master
# Cache bower dependencies for faster/network error-tolerant builds (provided cache invalidation occurs as expected)
cache:
  npm: false
  directories: null
dist: trusty
language: node_js
node_js:
  - "6.10.0"
notifications:
  email:
    on_success: never
    on_failure: change
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
after_success:
  - codeclimate-test-reporter < reports/coverage/client/lcov.txt
